Repository Chreggii/syntax-highlighter, pull requests merged in 2022-05, with the labels that each got.

#98 Update README.md
  README.md
Labels: documentation

#97 Feature/t8.4
  docker-compose.yml
  mlClassifier/java_model_data.pt
  mlClassifier/kotlin_model_data.pt
  mlClassifier/python3_model_data.pt
Labels: feature

#101 merge strategy for models
  mlClassifier/Readme.md
Labels: documentation

#145 fixed wideScreen bug
  frontend/src/app/app.component.scss
  frontend/src/app/components/page-about/page-about.component.scss
  frontend/src/app/components/page-formal-model/page-formal-model.component.html
  frontend/src/app/components/page-formal-model/page-formal-model.component.scss
  frontend/src/app/components/page-home/page-home.component.scss
  frontend/src/app/components/page-ml-model/page-ml-model.component.html
  frontend/src/app/components/page-ml-model/page-ml-model.component.scss
  frontend/src/app/components/top-navigation-bar/top-navigation-bar.component.html
  frontend/src/app/components/top-navigation-bar/top-navigation-bar.component.scss
Labels: bug

#149 Feature/frontend choose formatting
  frontend/src/app/components/code-presenter/code-presenter.component.html
  frontend/src/app/components/code-presenter/code-presenter.component.ts
  frontend/src/app/components/code-uploader/code-uploader.component.html
  frontend/src/app/components/code-uploader/code-uploader.component.ts
  frontend/src/app/components/h-code-values-handler/h-code-values-handler.component.spec.ts
  frontend/src/app/components/page-formal-model/page-formal-model.component.html
  frontend/src/app/components/page-formal-model/page-formal-model.component.ts
  frontend/src/app/components/page-ml-model/page-ml-model.component.html
  frontend/src/app/components/page-ml-model/page-ml-model.component.ts
  frontend/src/app/services/highlighter/highlight.service.ts
Labels: feature

#153 (Public API): changed mode to be part of a body in file requests
  mlClassifier/python3_model_data.pt
  publicAPI/src/highlight-file-html/highlight-file-html.controller.ts
  publicAPI/src/highlight-file/highlight-file.controller.ts
Labels: bug

#154 Feature/color mode choosing frontend
  frontend/src/app/app.module.ts
  frontend/src/app/components/code-presenter/code-presenter.component.html
  frontend/src/app/components/code-presenter/code-presenter.component.scss
  frontend/src/app/components/code-presenter/code-presenter.component.ts
  frontend/src/app/components/code-uploader/code-uploader.component.html
  frontend/src/app/components/code-uploader/code-uploader.component.scss
  frontend/src/app/components/code-uploader/code-uploader.component.spec.ts
  frontend/src/app/components/code-uploader/code-uploader.component.ts
  frontend/src/app/components/h-code-values-handler/h-code-values-handler.component.html
  frontend/src/app/components/h-code-values-handler/h-code-values-handler.component.scss
  frontend/src/app/components/h-code-values-handler/h-code-values-handler.component.spec.ts
  frontend/src/app/components/h-code-values-handler/h-code-values-handler.component.ts
  frontend/src/app/components/page-formal-model/page-formal-model.component.html
  frontend/src/app/components/page-formal-model/page-formal-model.component.ts
  frontend/src/app/components/page-ml-model/page-ml-model.component.html
  frontend/src/app/components/page-ml-model/page-ml-model.component.ts
  frontend/src/app/services/highlighter/highlight.service.spec.ts
  frontend/src/app/services/highlighter/highlight.service.ts
Labels: feature

#167 Documentation/frontend docstrings
  frontend/README.md
  frontend/docs/.nojekyll
  frontend/docs/assets/highlight.css
  frontend/docs/assets/icons.css
  frontend/docs/assets/icons.png
  frontend/docs/assets/icons@2x.png
  frontend/docs/assets/main.js
  frontend/docs/assets/search.js
  frontend/docs/assets/style.css
  frontend/docs/assets/widgets.png
  frontend/docs/assets/widgets@2x.png
  frontend/docs/classes/app_app_component.AppComponent.html
  frontend/docs/classes/app_app_module.AppModule.html
  frontend/docs/classes/app_app_routing_module.AppRoutingModule.html
  frontend/docs/classes/app_components_code_presenter_code_presenter_component.CodePresenterComponent.html
  frontend/docs/classes/app_components_code_uploader_code_uploader_component.CodeUploaderComponent.html
  frontend/docs/classes/app_components_page_about_page_about_component.PageAboutComponent.html
  frontend/docs/classes/app_components_page_formal_model_page_formal_model_component.PageFormalModelComponent.html
  frontend/docs/classes/app_components_page_home_page_home_component.PageHomeComponent.html
  frontend/docs/classes/app_components_page_ml_model_page_ml_model_component.PageMlModelComponent.html
  frontend/docs/classes/app_components_top_navigation_bar_top_navigation_bar_component.TopNavigationBarComponent.html
  frontend/docs/classes/app_pipes_safe_pipe.SafePipe.html
  frontend/docs/classes/app_services_highlighter_highlight_service.HighlightService.html
  frontend/docs/index.html
  frontend/docs/modules.html
  frontend/docs/modules/app_app_component.html
  frontend/docs/modules/app_app_module.html
  frontend/docs/modules/app_app_routing_module.html
  frontend/docs/modules/app_components_code_presenter_code_presenter_component.html
  frontend/docs/modules/app_components_code_uploader_code_uploader_component.html
  frontend/docs/modules/app_components_page_about_page_about_component.html
  frontend/docs/modules/app_components_page_formal_model_page_formal_model_component.html
  frontend/docs/modules/app_components_page_home_page_home_component.html
  frontend/docs/modules/app_components_page_ml_model_page_ml_model_component.html
  frontend/docs/modules/app_components_top_navigation_bar_top_navigation_bar_component.html
  frontend/docs/modules/app_functions_url_resolver_function.html
  frontend/docs/modules/app_pipes_safe_pipe.html
  frontend/docs/modules/app_services_highlighter_highlight_service.html
  frontend/docs/modules/environments_environment.html
  frontend/docs/modules/environments_environment_prod.html
  frontend/package-lock.json
  frontend/package.json
  frontend/sonar-project.properties
  frontend/src/app/components/code-uploader/code-uploader.component.html
  frontend/src/app/components/code-uploader/code-uploader.component.ts
  frontend/src/app/services/highlighter/highlight.service.ts
Labels: documentation

#173 how to run doc ml classifier
  mlClassifier/Readme.md
Labels: documentation

#178 SonarCloud fixes Frontend
  frontend/src/app/app.component.html
  frontend/src/app/app.component.spec.ts
  frontend/src/app/components/code-uploader/code-uploader.component.spec.ts
  frontend/src/app/components/code-uploader/mock-http-service.ts
  frontend/src/app/components/page-home/page-home.component.html
  frontend/src/app/components/page-home/page-home.component.scss
  frontend/src/app/services/highlighter/highlight.service.spec.ts
  frontend/src/test.ts
Labels: enhancement
